server:
  port: "8080"
  env: "dev"
  read_timeout: "10s"
  write_timeout: "15s"
  shutdown_timeout: "10s"

logger:
  level: "debug"

mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/zhiguang?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: "30m"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
